
version: '3.8'

services:
  mysql:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: taskdb
    ports:
      - "3307:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - ./mysql:/docker-entrypoint-initdb.d

  backend:
    build:
      context: ./backend
    depends_on:
      - mysql
    ports:
      - "5000:5000"
    restart: always

  auth:
    build:
      context: ./auth
    depends_on:
      - mysql
    ports:
      - "5001:5001"
    restart: always

  frontend:
    build:
      context: ./frontend
    ports:
      - "8080:80"
    restart: always

volumes:
  mysql_data:
